name: Unit tests

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: macos-12
    
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.app && /usr/bin/xcodebuild -version
      
    - name: Run tests
      run: xcodebuild clean build test -scheme Crypto2 -project Crypto2.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.5'
